version: "3.9"

services: 
  client:
    build: ./client
    # networks: 
    #   - nursery
    ports: 
      - "80:3000"
    volumes: 
      - .:/usr/frontend
  backend:
    build: ./api
    # networks: 
    #   -nursery
    ports: 
      - "8000:8000"
    volumes: 
      - .:/usr/backend
  # networks:
  #   nursery: 


  
  

      
    
